# Generated by Django 6.0 on 2026-07-09 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_expense_alter_purchase_date_alter_purchase_supplier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("supplier", models.CharField(default="Aliexpress", max_length=200)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SaleInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("customer", models.CharField(default="Generic", max_length=200)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name", "category__name"]},
        ),
        migrations.AlterModelOptions(
            name="purchase",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="purchase",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="stock.purchaseinvoice",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="stock.saleinvoice",
            ),
        ),
    ]
