# Generated by Django 6.0 on 2026-07-09 14:15

from collections import Counter
from django.db import migrations


def backfill_invoices(apps, schema_editor):
    PurchaseInvoice = apps.get_model("stock", "PurchaseInvoice")
    SaleInvoice = apps.get_model("stock", "SaleInvoice")
    Purchase = apps.get_model("stock", "Purchase")
    Sale = apps.get_model("stock", "Sale")

    # --- Compras: agrupar por día ---
    purchases = Purchase.objects.exclude(date__isnull=True).order_by("date")
    grouped = {}
    for p in purchases:
        grouped.setdefault(p.date.date(), []).append(p)

    for day, items in grouped.items():
        supplier = Counter(i.supplier for i in items).most_common(1)[0][0]
        invoice = PurchaseInvoice.objects.create(
            date=items[0].date,
            supplier=supplier,
        )
        Purchase.objects.filter(pk__in=[i.pk for i in items]).update(invoice=invoice)

    # --- Ventas: agrupar por día ---
    sales = Sale.objects.exclude(date__isnull=True).order_by("date")
    grouped = {}
    for s in sales:
        grouped.setdefault(s.date.date(), []).append(s)

    for day, items in grouped.items():
        customer = Counter(i.customer for i in items).most_common(1)[0][0]
        invoice = SaleInvoice.objects.create(
            date=items[0].date,
            customer=customer,
        )
        Sale.objects.filter(pk__in=[i.pk for i in items]).update(invoice=invoice)


def remove_invoices(apps, schema_editor):
    PurchaseInvoice = apps.get_model("stock", "PurchaseInvoice")
    SaleInvoice = apps.get_model("stock", "SaleInvoice")
    Purchase = apps.get_model("stock", "Purchase")
    Sale = apps.get_model("stock", "Sale")

    Purchase.objects.update(invoice=None)
    Sale.objects.update(invoice=None)
    PurchaseInvoice.objects.all().delete()
    SaleInvoice.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_invoices_add_models"),
    ]

    operations = [
        migrations.RunPython(backfill_invoices, remove_invoices),
    ]