# Generated by Django 6.0 on 2026-07-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_invoices_backfill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="date",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="date",
        ),
        migrations.AlterField(
            model_name="purchase",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="stock.purchaseinvoice",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="stock.saleinvoice",
            ),
        ),
    ]
