# Generated by Django 5.2.7 on 2026-08-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0009_otherincomecategory_otherincome"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
