# Generated by Django 5.2.7 on 2026-08-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0013_remove_saleinvoice_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="stock.tag"
            ),
        ),
    ]
