# Generated by Django 5.2.7 on 2026-09-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0014_tag_product_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
    ]
