from django.urls import path
from django.http import HttpResponseNotFound
from . import views
from . import api

urlpatterns = [
    path("", views.home, name="home"),
    # API pública de productos (solo lectura, sin login). Ver docs/api.md
    path("api/products/", api.api_product_list, name="api_product_list"),
    path("api/products/<int:pk>/", api.api_product_detail, name="api_product_detail"),
    path("favicon.ico", lambda request: HttpResponseNotFound()),
    path("top-productos/<str:period>/", views.top_products_view, name="top_products_period"),
    path("top-productos/", views.top_products_view, {"period": "mes"}, name="top_products"),
    # CRUD dedicado (vistas y templates propios por modelo)
    path("category/", views.category_list_view, name="category_list"),
    path("category/new/", views.category_form_view, name="category_new"),
    path("category/<int:pk>/edit/", views.category_form_view, name="category_edit"),
    path("tag/", views.tag_list_view, name="tag_list"),
    path("tag/new/", views.tag_form_view, name="tag_new"),
    path("tag/<int:pk>/edit/", views.tag_form_view, name="tag_edit"),
    path("expensecategory/", views.expensecategory_list_view, name="expensecategory_list"),
    path("expensecategory/new/", views.expensecategory_form_view, name="expensecategory_new"),
    path("expensecategory/<int:pk>/edit/", views.expensecategory_form_view, name="expensecategory_edit"),
    path("otherincomecategory/", views.otherincomecategory_list_view, name="otherincomecategory_list"),
    path("otherincomecategory/new/", views.otherincomecategory_form_view, name="otherincomecategory_new"),
    path("otherincomecategory/<int:pk>/edit/", views.otherincomecategory_form_view, name="otherincomecategory_edit"),
    path("customer/", views.customer_list_view, name="customer_list"),
    path("customer/new/", views.customer_form_view, name="customer_new"),
    path("customer/<int:pk>/edit/", views.customer_form_view, name="customer_edit"),
    path("expense/", views.expense_list_view, name="expense_list"),
    path("expense/new/", views.expense_form_view, name="expense_new"),
    path("expense/<int:pk>/edit/", views.expense_form_view, name="expense_edit"),
    path("otherincome/", views.otherincome_list_view, name="otherincome_list"),
    path("otherincome/new/", views.otherincome_form_view, name="otherincome_new"),
    path("otherincome/<int:pk>/edit/", views.otherincome_form_view, name="otherincome_edit"),
    path("product/", views.product_list_view, name="product_list"),
    path("compras/", views.purchase_list_view, name="purchase_list"),
    path("ventas/", views.sale_list_view, name="sale_list"),
    # Producto con marca y fotos
    path("product/new/", views.product_form_view, name="product_new"),
    path("product/<int:pk>/", views.product_detail_view, name="product_detail"),
    path("product/<int:pk>/edit/", views.product_form_view, name="product_edit"),
    path("product/<int:pk>/toggle-active/", views.product_toggle_active, name="product_toggle_active"),
    path("compras/new/", views.purchase_invoice_form_view, name="purchase_invoice_new"),
    path("compras/<int:pk>/edit/", views.purchase_invoice_form_view, name="purchase_invoice_edit"),
    path("compras/<int:pk>/", views.purchase_invoice_detail_view, name="purchase_invoice_detail"),
    path("ventas/new/", views.sale_invoice_form_view, name="sale_invoice_new"),
    path("ventas/<int:pk>/edit/", views.sale_invoice_form_view, name="sale_invoice_edit"),
    path("ventas/<int:pk>/", views.sale_invoice_detail_view, name="sale_invoice_detail"),
    path("resultados/<int:month_offset>/",
         views.month_result, name="month_result"),
    path("resultados/", views.month_result, {"month_offset": 0}),
    path("reportes/ventas-por-departamento/",
         views.sales_by_department, {"period": "mes"}, name="sales_by_department"),
    path("reportes/ventas-por-departamento/<str:period>/",
         views.sales_by_department, name="sales_by_department_period"),
    path("reportes/ventas-por-etiqueta/",
         views.sales_by_tag, {"period": "mes"}, name="sales_by_tag"),
    path("reportes/ventas-por-etiqueta/<str:period>/",
         views.sales_by_tag, name="sales_by_tag_period"),
    path("perfil/", views.user_profile, name="user_profile"),
    path("exportar/", views.export_data, name="export_data"),
    path("importar/", views.import_data, name="import_data"),
]